protected/controllers/AnggotaController.php
<?php
/********************************************************
 * dibuat oleh : Badiyanto  
 * tanggal     : 2017-10-10 01:25:44
 ********************************************************/
?>
<?php

class AnggotaController extends Controller
{
	/*****************************************************
	 * tiap tampilan menggunakan seting 2 kolom'//layouts/column2', 
	 * menggunakan file di'protected/views/layouts/column2.php'.
	 *****************************************************/
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/****************************************************************************
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 * pembatasan akses lewat fungsi dengan nama actionX... dengan allow
	 * user '*' semua user / tanpa login (guest)
	 * user '@' lewat login password
	 * user 'fredricls' hanya untuk admin
	 * deny  yang tidak boleh diakses
	 ****************************************************************************/
	
	public function accessRules()
	{
		return array(
			array('allow',  
			     // semua user boleh akse 'index' dan 'view' 
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', 
			     // user harus login utk akses'create' dan 'update' a
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', 
			     // hanya user admin yang boleh akses'admin' dan 'delete' 
				'actions'=>array('admin','delete'),
				'users'=>array('fredricls'),
			),
			array('deny',  // tidak boleh utk semua user
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 * menampilkan detail 
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Anggota;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Anggota']))
		{
			$model->attributes=$_POST['Anggota'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Anggota']))
		{
			$model->attributes=$_POST['Anggota'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view),
 			// we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,
			    'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Anggota');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 * halaman admin utk menajemen data
	 */
	public function actionAdmin()
	{
		$model=new Anggota('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Anggota']))
			$model->attributes=$_GET['Anggota'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary
	 * key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Anggota::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 * ajax untuk validasi
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='anggota-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/KotaController.php
<?php
/********************************************************
 * dibuat oleh : FredricLesomar  
 * tanggal     : 2017-09-26 04:21:18
 ********************************************************/
?>
<?php

class KotaController extends Controller
{
	/*****************************************************
	 * tiap tampilan menggunakan seting 2 kolom'//layouts/column2', 
	 * menggunakan file di'protected/views/layouts/column2.php'.
	 *****************************************************/
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/****************************************************************************
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 * pembatasan akses lewat fungsi dengan nama actionX... dengan allow
	 * user '*' semua user / tanpa login (guest)
	 * user '@' lewat login password
	 * user 'fredricls' hanya untuk admin
	 * deny  yang tidak boleh diakses
	 ****************************************************************************/
	
	public function accessRules()
	{
		return array(
			array('allow',  
			     // semua user boleh akse 'index' dan 'view' 
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', 
			     // user harus login utk akses'create' dan 'update' a
				'actions'=>array('create','update', 'daftarKota', 'provinsi'),
				'users'=>array('@'),
			),
			array('allow', 
			     // hanya user admin yang boleh akses'admin' dan 'delete' 
				'actions'=>array('admin','delete'),
				'users'=>array('fredricls'),
			),
			array('deny',  // tidak boleh utk semua user
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 * menampilkan detail 
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	public function actionDaftarKota()
	{
		$this->render('daftarKota');
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Kota;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Kota']))
		{
			$model->attributes=$_POST['Kota'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_kota));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	public function actionProvinsi()
	{
		$model=new Kota;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Kota']))
		{
			$model->attributes=$_POST['Kota'];
			$id=$_POST['Kota']['id_provinsi'];

			$this->redirect(array('daftarKota','id'=>$id));
		}

		$this->render('provinsi',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Kota']))
		{
			$model->attributes=$_POST['Kota'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_kota));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view),
 			// we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,
			    'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Kota');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 * halaman admin utk menajemen data
	 */
	public function actionAdmin()
	{
		$model=new Kota('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Kota']))
			$model->attributes=$_GET['Kota'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary
	 * key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Kota::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 * ajax untuk validasi
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='kota-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/KotakController.php
<?php

class KotakController extends Controller
{
	public function actionIndex()
	{
		$this->render('index');
	}

	public function actionHitung()
	{
		$model=new Kotak;
		$model->unsetAttributes();

	    if(isset($_POST['Kotak']))
	    {
	    	$model->attributes=$_POST['Kotak'];
	        $panjang=$_POST['Kotak']['panjang'];
	        $lebar=$_POST['Kotak']['lebar'];
	        $this->redirect(array('luas', 'panjang'=>$panjang, 'lebar'=>$lebar));
	    }

		$this->layout='column2';
		$this->render('hitung', array('model'=>$model));
	}

	public function actionLuas()
	{
		$model=new Kotak;
		$model->unsetAttributes();

		if (isset($_GET['Kotak'])) 
			$model->attributes=$_GET['Kotak'];
		$this->layout='column2';
		$this->render('luas', array('model'=>$model));
		
	}
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		
		if(Yii::app()->user->isGuest)
			$this->redirect(array('login'));
		else
		{
			$this->layout='column2';
			$this->render('index');
		}
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Terimakasih telah menghubungi kami, secepatnya akan kami respon.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/********************************
	 * Halama Login
	 ********************************/
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/************************************
	 * keluar/logut.
	 ************************************/

	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}

	/**************************************** 
         bagian ini hanya prototipe 
          bisa diubah sendiri sesui kebutuhan
       *****************************************/

	public function actionTblUser()
	{
		// contoh memanggil view tblUser.php
		$this->layout='column2';
		$this->render('tblUser');
	}
	public function actionGantiPassword()
	{
		// contoh memanggil view gantiPassword.php
		$this->layout='column2';
		$this->render('gantiPassword');
	}
	
	public function actionTblKota()
	{
		// contoh memanggil view tblKota.php
		$this->layout='column2';
		$this->render('tblKota');
	}
	public function actionTblPropinsi()
	{
		// contoh memanggil view tblKota.php
		$this->layout='column2';
		$this->render('tblPropinsi');
	}
	
	public function actionHelp()
	{
		// contoh memanggil view help.php
		$this->layout='column2';
		$this->render('help');
	}

	public function actionHello()
	{
		$this->layout='column2';
		$this->render('hello');
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>

	<!-- menu sebelah kiri-->
	<div class="row">
	<div class="span2" id="sidebar">
	 <?php  $this->widget('bootstrap.widgets.TbMenu', array(
          'type'=>'list',
          'items'=>array(
                        array('label'=>'CONTROLL'),
                        array('label'=>'Home', 'icon'=>'home', 'url'=>array('site/index')),
                      //  array('label'=>'User', 'icon'=>'user', 'url'=>array('site/tblUser')),
                    //    array('label'=>'Ganti Password', 'icon'=>'pencil','url'=>array('site/gantiPassword')),
                        array('label'=>'Perekaman Lokasi'),
                        array('label'=>'Provinsi', 'icon'=>'cog', 'url'=>array('provinsi/index')),
                        array('label'=>'Kota', 'icon'=>'cog', 'url'=>array('kota/index')),
                 //       array('label'=>'Persegi', 'icon'=>'book', 'url'=>array('kotak/hitung')),
                        array('label'=>'Kota per Provinsi', 'icon'=>'cog', 'url'=>array('kota/provinsi')),
                        array('label'=>'Pembukuan Utang'),
                        array('label'=>'Member', 'icon'=>'user', 'url'=>array('anggota/index')),
                        array('label'=>'Pekerjaan', 'icon'=>'user', 'url'=>array('pekerjaan/index')),
                        array('label'=>'Pinjaman', 'icon'=>'tags', 'url'=>array('pinjaman/index')),
                        array('label'=>'Angsuran', 'icon'=>'tags', 'url'=>array('angsuran/angsuranPerAnggota')),
                        array('label'=>'Help', 'icon'=>'flag', 'url'=>array('site/help')),
                ),
            
              )); 
		
	?>
	</div> <!-- sidebar -->
 
	<!-- halaman isi -->
	<div class="span10" id="main-content">
		<?php echo $content; ?>
	</div><!-- content -->
    </div>
   </div>
 <?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />
    <!-- mamanggil CSS bootstrap -->
	<?php  Yii::app()->bootstrap->registerYiiCss(); ?> 
	
	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>
<div class="container" id="page">
	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->
	
    <!-- bagian menu utama atas Menggunakan CMenu-->
	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>array('/site/index')),
				array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
				array('label'=>'Contact', 'url'=>array('/site/contact')),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->tbbreadcrumbs)):?>
		<?php $this->widget('bootstrap.widgets.TbBreadcrumbs', array(
			'links'=>$this->tbbreadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php  echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
<!--		Developed &copy; <?php echo date('Y'); ?> by Fredric Lesomar.<br/>
		<?php echo Yii::powered(); ?> -->
		Hubungi Kami :<br/>
		 Jam Kerja : Senin – Jumat, Pukul : 09:00 – 09:30<br/>
 WhatsApp : 0812852256XX<br/>
 Alamat : Jalan Kenangan, Kode Pos 1337
		
	</div><!-- footer -->
	
	
 
 
</div><!-- page -->

</body>
</html>